//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institut_Ashralite_Adm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDIVIDU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INDIVIDU()
        {
            this.COURS = new HashSet<COURS>();
            this.INSCRIPTION = new HashSet<INSCRIPTION>();
            this.PRESENCE = new HashSet<PRESENCE>();
        }
    
        public int ID { get; set; }
        public int ID_CIVILITE { get; set; }
        public int ID_METIER { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public string EMAIL { get; set; }
        public string PORTABLE { get; set; }
        public string COMMENTAIRE { get; set; }
        public bool ACTIF { get; set; }
        public System.DateTime DATE_ACTIF { get; set; }
        public string UTILISATEUR_CREATION { get; set; }
        public string UTILISATEUR_MODIFICATION { get; set; }
        public System.DateTime DATE_CREATION { get; set; }
        public System.DateTime DATE_MODIFICATION { get; set; }
        public string SEMAINE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURS> COURS { get; set; }
        public virtual REF_CIVILITE REF_CIVILITE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPTION> INSCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESENCE> PRESENCE { get; set; }
        public virtual REF_METIER REF_METIER { get; set; }
    }
}
