//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institut_Ashralite_Adm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int id { get; set; }
        //[Required(ErrorMessage = "Nom et mot de pass obligatoire")]
        public string Name { get; set; }
        //[Required(ErrorMessage = "Nom et mot de pass obligatoire")]

        public string Password { get; set; }

        public string LoginMessageErrer { get; set; }
    }
}
